### ISSUE TITLE
Platform 1 error

### ISSUE THREAD

**Issue by dsrawat984** [stelace/stelace#702]
Hi Guys,

I am getting the below error whenever marketplace-demo web is trying to access the api server which I have hosted in a machine. Here is the example from one of the APIs url 78.56.34.89:4100/config.

```json
{"context":{"application":"stelace-core","logLevel":50,"err":{"name":"Error","message":"Platform 1 does not exist.","stack":"Error: Platform 1 does not exist.\n    at getPlatformEnvData (/usr/src/app/src/redis.js:191:24)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:94:5)\n    at async getConnection (/usr/src/app/src/models/index.js:96:28)\n    at async getModels (/usr/src/app/src/models/index.js:142:34)\n    at async /usr/src/app/src/services/apiKey.js:453:24\n    at async newHandler (/usr/src/app/src/cote/CustomResponder.js:33:24)","statusCode":500,"params":[]},"custom":{"metrics":{"statusCode":500,"method":"GET","path":"/config"},"requestContext":{"method":"GET","routeName":"config.read","ip":"::ffff:117.203.29.51","requestId":"bee0ed20-752a-4640-b1a5-e0f8501407a4","selectedVersion":"2019-05-20","platformVersion":"2019-05-20","latestVersion":"2019-05-20","platformId":"1","env":"test"}}},"message":"Error","sequence":57,"time":1625301089282,"version":"1.0.0"}
``` 

Can somebody help me on this. Thank you.

**Comment by abruere** [comment]
Hi, you’ve to create a platform in stelace backend and get related API keys to use in marketplace-demo front-end.

You can use `yarn seed` after [installing](https://github.com/stelace/stelace#setup) stelace server to create this first platform with API keys before following the [Quick Start](https://stelace.com/docs/getting-started.html) guide.

I hope this helps !
