### ISSUE TITLE
how not to use the docker compose

### ISSUE THREAD

**Issue by JamesDAdams** [stelace/stelace#744]
Hi,

I tried not to use your docker compose and connect me directly to containers that have the official images (because later I plan to use postgres on AWS) but I have this error when I do a **yarn seed** (the **yarn knex migrate:latest** works)

The error : 

`````
jamesadams@jamesadams-ubuntu:~/Documents/Dev/test/back$ yarn knex migrate:latest
yarn run v1.22.17
$ knex migrate:latest
Already up to date
Done in 0.52s.
jamesadams@jamesadams-ubuntu:~/Documents/Dev/test/back$ yarn seed
yarn run v1.22.17
$ INSTANT_DATA=true npm test scripts/instantData.js

> stelace-server@1.0.0-beta.8 pretest /home/jamesadams/Documents/Dev/test/back
> NODE_ENV=test node test/pretest.js

email plugin enabled
rating plugin enabled
saved-search plugin enabled
stelace-search-filter-dsl-parser plugin enabled

> stelace-server@1.0.0-beta.8 test /home/jamesadams/Documents/Dev/test/back
> NODE_ENV=test ava --c $(node -p 'Math.max(os.cpus().length - 2, 1)') "scripts/instantData.js"


email plugin enabled
rating plugin enabled
saved-search plugin enabled
stelace-search-filter-dsl-parser plugin enabled
migration file "20200713111032_init.js" failed
migration failed with error: 
    SELECT public.create_hypertable(
      's1_test."event"', 'createdTimestamp'
      
    )
   - function public.create_hypertable(unknown, unknown) does not exist
  beforeEach hook for initializing data

  Rejected promise returned by test. Reason:

  Error {
    response: Response {
      _events: {},
      _eventsCount: 0,
      _maxListeners: undefined,
      accepted: false,
      badRequest: false,
      body: {
        _message: `␊
            SELECT public.create_hypertable(␊
              's1_test."event"', 'createdTimestamp'␊
              ␊
            )␊
           - function public.create_hypertable(unknown, unknown) does not exist`,
        _stack: Array [ … ],
        code: '42883',
        message: 'Internal Server Error',
        statusCode: 500,
      },
      buffered: true,
      clientError: false,
      created: false,
      error: Error {
        method: 'POST',
        path: '/store/platforms/1/database/migrate',
        status: 500,
        text: '{"code":"42883","message":"Internal Server Error","statusCode":500,"_stack":["error: ","    SELECT public.create_hypertable(","      \'s1_test.\\"event\\"\', \'createdTimestamp\'","      ","    )","   - function public.create_hypertable(unknown, unknown) does not exist","    at Parser.parseErrorMessage (/home/jamesadams/Documents/Dev/test/back/node_modules/pg-protocol/src/parser.ts:369:69)","    at Parser.handlePacket (/home/jamesadams/Documents/Dev/test/back/node_modules/pg-protocol/src/parser.ts:188:21)","    at Parser.parse (/home/jamesadams/Documents/Dev/test/back/node_modules/pg-protocol/src/parser.ts:103:30)","    at Socket.<anonymous> (/home/jamesadams/Documents/Dev/test/back/node_modules/pg-protocol/src/index.ts:7:48)","    at Socket.emit (events.js:223:5)","    at Socket.EventEmitter.emit (domain.js:475:20)","    at addChunk (_stream_readable.js:309:12)","    at readableAddChunk (_stream_readable.js:290:11)","    at Socket.Readable.push (_stream_readable.js:224:10)","    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)"],"_message":"\\n    SELECT public.create_hypertable(\\n      \'s1_test.\\"event\\"\', \'createdTimestamp\'\\n      \\n    )\\n   - function public.create_hypertable(unknown, unknown) does not exist"}',
        message: 'cannot POST /store/platforms/1/database/migrate (500)',
      },
      files: undefined,
      forbidden: false,
      header: {
        'access-control-allow-credentials': 'true',
        connection: 'close',
        'content-encoding': 'gzip',
        'content-type': 'application/json',
        date: 'Thu, 09 Dec 2021 19:42:19 GMT',
        server: 'stelace-server',
        'transfer-encoding': 'chunked',
        vary: 'origin,access-control-request-method,access-control-request-headers',
      },
      headers: {
        'access-control-allow-credentials': 'true',
        connection: 'close',
        'content-encoding': 'gzip',
        'content-type': 'application/json',
        date: 'Thu, 09 Dec 2021 19:42:19 GMT',
        server: 'stelace-server',
        'transfer-encoding': 'chunked',
        vary: 'origin,access-control-request-method,access-control-request-headers',
      },
      info: false,
      links: {},
      noContent: false,
      notAcceptable: false,
      notFound: false,
      ok: false,
      pipe: Function {},
      redirect: false,
      redirects: [],
      req: ClientRequest {
        _contentLength: 0,
        _ended: true,
        _events: Object { … },
        _eventsCount: 3,
        _hasBody: true,
        _header: `POST /store/platforms/1/database/migrate HTTP/1.1␍␊
        Host: 127.0.0.1:43589␍␊
        Accept-Encoding: gzip, deflate␍␊
        x-stelace-system-key: system␍␊
        x-stelace-env: test␍␊
        Connection: close␍␊
        Content-Length: 0␍␊
        ␍␊
        `,
        _headerSent: true,
        _last: true,
        _maxListeners: undefined,
        _onPendingData: Function noopPendingOutput {},
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _trailer: '',
        aborted: false,
        agent: Agent { … },
        chunkedEncoding: false,
        connection: Socket { … },
        finished: true,
        maxHeadersCount: null,
        method: 'POST',
        outputData: [],
        outputSize: 0,
        parser: null,
        path: '/store/platforms/1/database/migrate',
        res: IncomingMessage { … },
        sendDate: false,
        shouldKeepAlive: false,
        socket: Socket { … },
        socketPath: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        useChunkedEncodingByDefault: true,
        writable: true,
        [Symbol(kNeedDrain)]: false,
        [Symbol(isCorked)]: false,
        [Symbol(kOutHeaders)]: Object { … },
      },
      request: Request {
        _agent: false,
        _callback: Function {},
        _enableHttp2: false,
        _endCalled: true,
        _events: Object { … },
        _eventsCount: 1,
        _formData: null,
        _fullfilledPromise: Promise {},
        _header: Object { … },
        _maxListeners: undefined,
        _maxRedirects: 5,
        _query: [],
        _redirectList: [],
        _redirects: 0,
        _resBuffered: true,
        _streamRequest: false,
        called: true,
        cookies: '',
        header: Object { … },
        host: '127.0.0.1:43589',
        method: 'POST',
        protocol: 'http:',
        qs: {},
        qsRaw: [],
        req: ClientRequest { … },
        res: IncomingMessage { … },
        response: [Circular],
        url: 'http://127.0.0.1:43589/store/platforms/1/database/migrate',
        writable: true,
      },
      res: IncomingMessage {
        _consuming: false,
        _dumped: false,
        _events: Object { … },
        _eventsCount: 3,
        _maxListeners: undefined,
        _readableState: ReadableState [ … ],
        aborted: false,
        client: Socket { … },
        complete: true,
        connection: Socket { … },
        headers: Object { … },
        httpVersion: '1.1',
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        method: null,
        on: Function {},
        rawHeaders: Array [ … ],
        rawTrailers: [],
        readable: false,
        req: ClientRequest { … },
        setEncoding: Function {},
        socket: Socket { … },
        statusCode: 500,
        statusMessage: 'Internal Server Error',
        text: '{"code":"42883","message":"Internal Server Error","statusCode":500,"_stack":["error: ","    SELECT public.create_hypertable(","      \'s1_test.\\"event\\"\', \'createdTimestamp\'","      ","    )","   - function public.create_hypertable(unknown, unknown) does not exist","    at Parser.parseErrorMessage (/home/jamesadams/Documents/Dev/test/back/node_modules/pg-protocol/src/parser.ts:369:69)","    at Parser.handlePacket (/home/jamesadams/Documents/Dev/test/back/node_modules/pg-protocol/src/parser.ts:188:21)","    at Parser.parse (/home/jamesadams/Documents/Dev/test/back/node_modules/pg-protocol/src/parser.ts:103:30)","    at Socket.<anonymous> (/home/jamesadams/Documents/Dev/test/back/node_modules/pg-protocol/src/index.ts:7:48)","    at Socket.emit (events.js:223:5)","    at Socket.EventEmitter.emit (domain.js:475:20)","    at addChunk (_stream_readable.js:309:12)","    at readableAddChunk (_stream_readable.js:290:11)","    at Socket.Readable.push (_stream_readable.js:224:10)","    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)"],"_message":"\\n    SELECT public.create_hypertable(\\n      \'s1_test.\\"event\\"\', \'createdTimestamp\'\\n      \\n    )\\n   - function public.create_hypertable(unknown, unknown) does not exist"}',
        trailers: {},
        upgrade: false,
        url: '',
      },
      serverError: true,
      setEncoding: Function bound  {},
      status: 500,
      statusCode: 500,
      statusType: 5,
      text: '{"code":"42883","message":"Internal Server Error","statusCode":500,"_stack":["error: ","    SELECT public.create_hypertable(","      \'s1_test.\\"event\\"\', \'createdTimestamp\'","      ","    )","   - function public.create_hypertable(unknown, unknown) does not exist","    at Parser.parseErrorMessage (/home/jamesadams/Documents/Dev/test/back/node_modules/pg-protocol/src/parser.ts:369:69)","    at Parser.handlePacket (/home/jamesadams/Documents/Dev/test/back/node_modules/pg-protocol/src/parser.ts:188:21)","    at Parser.parse (/home/jamesadams/Documents/Dev/test/back/node_modules/pg-protocol/src/parser.ts:103:30)","    at Socket.<anonymous> (/home/jamesadams/Documents/Dev/test/back/node_modules/pg-protocol/src/index.ts:7:48)","    at Socket.emit (events.js:223:5)","    at Socket.EventEmitter.emit (domain.js:475:20)","    at addChunk (_stream_readable.js:309:12)","    at readableAddChunk (_stream_readable.js:290:11)","    at Socket.Readable.push (_stream_readable.js:224:10)","    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)"],"_message":"\\n    SELECT public.create_hypertable(\\n      \'s1_test.\\"event\\"\', \'createdTimestamp\'\\n      \\n    )\\n   - function public.create_hypertable(unknown, unknown) does not exist"}',
      type: 'application/json',
      unauthorized: false,
      unprocessableEntity: false,
    },
    status: 500,
    message: 'Internal Server Error',
  }

  › Request.callback (node_modules/superagent/src/node/index.js:879:15)
  › fn (node_modules/superagent/src/node/index.js:1130:18)
  › IncomingMessage.<anonymous> (node_modules/superagent/src/node/parsers/json.js:19:7)
  › Unzip.<anonymous> (node_modules/superagent/src/node/unzip.js:54:12)

  ─

  1 hook failed
npm ERR! Test failed.  See above for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by woyuen** [comment]
Sorry for my late answer.

As your error messages shows, it tries to use hypertables which are a feature from TimescaleDB : https://github.com/stelace/stelace/pull/349
`function public.create_hypertable(unknown, unknown) does not exist`

As you're using the PostgreSQL image, I suggest you to use the master branch.

**Comment by woyuen** [comment]
I'm closing this issue but don't hesitate to post additional messages if needed.
