### ISSUE TITLE
Elasticsearch does not start properly on dev environment

### ISSUE THREAD

**Issue by saniales** [stelace/stelace#758]
I get this error when I run `yarn docker:db`

```
ubuntu@ip-172-31-2-255:~/stelace$ docker-compose up redis elasticsearch postgresql
[+] Running 3/0
 ⠿ Container stelace-redis-1          Running                                                                      0.0s
 ⠿ Container stelace-elasticsearch-1  Created                                                                      0.0s
 ⠿ Container stelace-postgresql-1     Running                                                                      0.0s
Attaching to stelace-elasticsearch-1, stelace-postgresql-1, stelace-redis-1
stelace-elasticsearch-1  | Exception in thread "main" java.lang.RuntimeException: starting java failed with [137]
stelace-elasticsearch-1  | output:
stelace-elasticsearch-1  |
stelace-elasticsearch-1  | error:
stelace-elasticsearch-1  | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
stelace-elasticsearch-1  |      at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
stelace-elasticsearch-1  |      at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
stelace-elasticsearch-1  |      at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
stelace-elasticsearch-1  |      at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)
stelace-elasticsearch-1 exited with code 1
```

**Comment by saniales** [comment]
https://discuss.elastic.co/t/cant-start-elasticsearch-on-ubuntu-19-10/204353

I solved by buying a bigger machine, probably minimum requirements must be stated somewhere
