### ISSUE TITLE
Issue in installing the Package

### ISSUE THREAD

**Issue by reyasfaizal** [stelace/stelace#773]
Cloned the Repository
Installed Docker for Mac
Started the Docker

Issue while trying to run 

yarn plugins

Error: Cannot find module stelace-search-filter-dsl-parser/package.json

Environment:
Apple Mac M1 Pro
Mac OS 13.1

**Comment by woyuen** [comment]
Hi @reyasfaizal, thanks for reporting this error.

We haven't been able to reproduce it.
We exclusively work in Linux environment and use Docker to allow users who work with other OSs to run the code.

We think there are two possibilities:
- Docker for Mac doesn't work as expected
- you run Docker but trigger scripts that works outside of Docker

In your message, you try to run `yarn plugins`, however if you're using Docker you should run it within Docker via `docker-compose run --rm api yarn plugins`.

**Comment by reyasfaizal** [comment]
Hi @woyuen, thanks for the reply

We were able to host the application in one of our ubuntu servers.

We are trying to run the app without using Docker.

We have all the dependencies installed. When we try to run 

`yarn seed`

I'm receiving the below error.

```
yarn run v1.22.19
$ INSTANT_DATA=true npm test scripts/instantData.js

> stelace-server@1.0.0-beta.8 pretest
> NODE_ENV=test node test/pretest.js

email plugin enabled
rating plugin enabled
saved-search plugin enabled
stelace-search-filter-dsl-parser plugin enabled
(node:28973) [DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated.
Error: socket hang up
    at connResetException (internal/errors.js:609:14)
    at Socket.socketOnEnd (_http_client.js:458:23)
    at Socket.emit (events.js:326:22)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET',
  response: undefined
}

> stelace-server@1.0.0-beta.8 test
> NODE_ENV=test ava --c $(node -p 'Math.max(os.cpus().length - 2, 1)') "scripts/instantData.js"


⠦ email plugin enabled
⠇ rating plugin enabled
⠏ saved-search plugin enabled
⠙ stelace-search-filter-dsl-parser plugin enabled
⠸ (node:29021) [DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
The application is hosted in DigitalOcean, with Ubuntu 22.04 (LTS) x64 as OS

**Comment by woyuen** [comment]
The socket hang up according your error message. That's probably because the databases aren't up. Please ensure they are running before running `yarn seed`.
